name: Build launcher and bump version number
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  bump-version-number:
    outputs:
      version_number: ${{ steps.get_new_version.outputs.version_no }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: check commit type
        shell: bash
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"release:"* ]]; then
              echo "Continuing to build as release"
          else
              echo "Not a release commit, exiting (note: this may take 5-10 seconds)"
              gh run cancel ${{ github.run_id }}
              gh run watch ${{ github.run_id }}
          fi
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: setup git
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          
      - name: update file version
        id: get_new_version
        run: |
          #parsed string
          
          export old_version=$(cat src/AssemblyInfo.cs|sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
          export new_version=$(cat src/AssemblyInfo.cs | tail -n 1 | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p' |  awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
          echo $old_version
          echo $new_version
          echo "version=$new_version" >> $GITHUB_ENV
          echo "version_no=$new_version" >> "$GITHUB_OUTPUT"
          sed -i "s/$old_version/$new_version/g" src/AssemblyInfo.cs 

      - name: push to origin
        run: |
          git add src/AssemblyInfo.cs
          git commit -m "Update file version"
          git push origin main

  deploy:
    needs: bump-version-number
    runs-on: windows-latest
    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Output commit type
        run: echo " ${{env.OUTPUT1}} $OUTPUT1"
        env:
            OUTPUT1: ${{ needs.bump-version-number.outputs.version_number}}
            
      - name: Checkout cdn repository
        uses: actions/checkout@v4
        with:
          repository: 'flarialmc/newcdn'
          ref: 'main'
          path: 'cdn'
          token: ${{secrets.ACTIONS_GITHUB_TOKEN}}
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: src/global.json

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          ls
          cd src
          cat AssemblyInfo.cs
          msbuild -t:Restore Flarial.Launcher.csproj
          msbuild /p:Configuration=Release /m Flarial.Launcher.csproj
          
      - name: update new version
        if: success()
        run: |
          cd cdn
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@example.com"
          export new_version="${{ env.OUTPUT1 }}"
          contents="$(jq '.version = "'$new_version'"' launcher/launcherVersion.txt)" && \
          echo -E "${contents}" > launcher/launcherVersion.txt
          cat launcher/launcherVersion.txt
          git add launcher/launcherVersion.txt
          git commit -m "Bump launcher version"
          git push origin main
          cp D:/a/launcher/launcher/src/bin/Release/net481/Flarial.Launcher.exe ./launcher/Flarial.Launcher.exe
          git add launcher/Flarial.Launcher.exe
          git commit -a -m "Update launcher"
          git push origin main
        env:
          OUTPUT1: ${{ needs.bump-version-number.outputs.version_number}}
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ needs.bump-version-number.outputs.version_number }}
          release_name: Release ${{ needs.bump-version-number.outputs.version_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Launcher to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: D:/a/launcher/launcher/src/bin/Release/net481/Flarial.Launcher.exe
          asset_name: Flarial.Launcher.exe
          asset_content_type: application/vnd.microsoft.portable-executable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
